### ISSUE TITLE
The docker-network, some problems - is this a Solution ?

### ISSUE THREAD

**Issue by Inkimar** [mskyttner/nub-docker#10]
**Note**
We would need to look at this a bit closer, this is an issue that is linked to dnsdock - and understanding this fully will help our efforts regarding other docker-projects.

**Description of the problem.**
Logging into the elk-container ( docker exec -it clbdocker_elk_1 bash ) 
Running 'apt update'
cannot find the ' http://archive.ubuntu.com/ubuntu'
_Is this a local problem or do others also have this problem_ ? 

**Solving the problem**
Adding the following to the docker-compos.yml-file
```
  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    command: --log-facility=-
    container_name: dnsmasq
    cap_add: 
      - NET_ADMIN 
    ports:
      - 172.17.0.1:53:53/tcp
      - 172.17.0.1:53:53/udp
```

If all services are up after your editing:

1. docker-compose stop dnsdock
2. docker-compose run -d dnsmasq
3. docker-compose stop dnsmasq
4. docker-compose start -d dnsdock

 $ docker exec -it clbdocker_elk_1 bash
root@2201e41019cb:/# apt update
works
